### ISSUE TITLE
choose library for GUI

### ISSUE THREAD

**Issue by MaleeGrenella** [brh033/CSC-Industrial-Safety-Monitor#1]
Research Python libraries that would be good to use for a GUI that displays graphs and uses a touchscreen. Post comments on which GUI should be used and why.

**Comment by MaleeGrenella** [comment]
Dear PyGui might be a good library because it has a lot of ways we could utilize the UI to show data. It has add-ons that are good for making UIs and works really well with Python. Also, it is best used for GUIs on Windows, Mac, Unix and Linux.

**Comment by shashi369** [comment]
works for me

**Comment by brh033** [comment]
-from gauge import Gauge
-import adafruit_ili9341
-import adafruit_display_text
-import adafruit_display_shapes
